// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy2IG9gKKKcZf_3fqJGFvxBnZSXAtI1z0',
    appId: '1:167504854839:web:906e30b21652cfe975e4b2',
    messagingSenderId: '167504854839',
    projectId: 'jobmate-4d082',
    authDomain: 'jobmate-4d082.firebaseapp.com',
    storageBucket: 'jobmate-4d082.firebasestorage.app',
    measurementId: 'G-VTKGGVMSRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdoO7uoFq01LsJZfo_-6yJwYoMvD3lvS4',
    appId: '1:167504854839:android:065d64dfcd74666475e4b2',
    messagingSenderId: '167504854839',
    projectId: 'jobmate-4d082',
    storageBucket: 'jobmate-4d082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA70pHQCK6KicY_Vhbb910LbYjF4mLt3uk',
    appId: '1:167504854839:ios:a4e16d476a2b8d9475e4b2',
    messagingSenderId: '167504854839',
    projectId: 'jobmate-4d082',
    storageBucket: 'jobmate-4d082.firebasestorage.app',
    iosBundleId: 'com.example.jobmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA70pHQCK6KicY_Vhbb910LbYjF4mLt3uk',
    appId: '1:167504854839:ios:a4e16d476a2b8d9475e4b2',
    messagingSenderId: '167504854839',
    projectId: 'jobmate-4d082',
    storageBucket: 'jobmate-4d082.firebasestorage.app',
    iosBundleId: 'com.example.jobmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy2IG9gKKKcZf_3fqJGFvxBnZSXAtI1z0',
    appId: '1:167504854839:web:9c0a18acdc58f26675e4b2',
    messagingSenderId: '167504854839',
    projectId: 'jobmate-4d082',
    authDomain: 'jobmate-4d082.firebaseapp.com',
    storageBucket: 'jobmate-4d082.firebasestorage.app',
    measurementId: 'G-KZE0PHCJHZ',
  );
}
